In \[1\]:

    import pandas as pd
    import numpy as np
    import random

In \[4\]:

    df = pd.read_csv(r'C:\Users\D_COMP_RSL-14\Downloads\country_wise_latest.csv')
    df

Out\[4\]:

|     | Country/Region     | Confirmed | Deaths | Recovered | Active | New cases | New deaths | New recovered | Deaths / 100 Cases | Recovered / 100 Cases | Deaths / 100 Recovered | Confirmed last week | 1 week change | 1 week % increase | WHO Region            |
|-----|--------------------|-----------|--------|-----------|--------|-----------|------------|---------------|--------------------|-----------------------|------------------------|---------------------|---------------|-------------------|-----------------------|
| 0   | Afghanistan        | 36263     | 1269   | 25198     | 9796   | 106       | 10         | 18            | 3.50               | 69.49                 | 5.04                   | 35526               | 737           | 2.07              | Eastern Mediterranean |
| 1   | Albania            | 4880      | 144    | 2745      | 1991   | 117       | 6          | 63            | 2.95               | 56.25                 | 5.25                   | 4171                | 709           | 17.00             | Europe                |
| 2   | Algeria            | 27973     | 1163   | 18837     | 7973   | 616       | 8          | 749           | 4.16               | 67.34                 | 6.17                   | 23691               | 4282          | 18.07             | Africa                |
| 3   | Andorra            | 907       | 52     | 803       | 52     | 10        | 0          | 0             | 5.73               | 88.53                 | 6.48                   | 884                 | 23            | 2.60              | Europe                |
| 4   | Angola             | 950       | 41     | 242       | 667    | 18        | 1          | 0             | 4.32               | 25.47                 | 16.94                  | 749                 | 201           | 26.84             | Africa                |
| ... | ...                | ...       | ...    | ...       | ...    | ...       | ...        | ...           | ...                | ...                   | ...                    | ...                 | ...           | ...               | ...                   |
| 182 | West Bank and Gaza | 10621     | 78     | 3752      | 6791   | 152       | 2          | 0             | 0.73               | 35.33                 | 2.08                   | 8916                | 1705          | 19.12             | Eastern Mediterranean |
| 183 | Western Sahara     | 10        | 1      | 8         | 1      | 0         | 0          | 0             | 10.00              | 80.00                 | 12.50                  | 10                  | 0             | 0.00              | Africa                |
| 184 | Yemen              | 1691      | 483    | 833       | 375    | 10        | 4          | 36            | 28.56              | 49.26                 | 57.98                  | 1619                | 72            | 4.45              | Eastern Mediterranean |
| 185 | Zambia             | 4552      | 140    | 2815      | 1597   | 71        | 1          | 465           | 3.08               | 61.84                 | 4.97                   | 3326                | 1226          | 36.86             | Africa                |
| 186 | Zimbabwe           | 2704      | 36     | 542       | 2126   | 192       | 2          | 24            | 1.33               | 20.04                 | 6.64                   | 1713                | 991           | 57.85             | Africa                |

187 rows × 15 columns

In \[6\]:

    df = pd.read_csv("country_wise_latest.csv")
    df

Out\[6\]:

|     | Country/Region     | Confirmed | Deaths | Recovered | Active | New cases | New deaths | New recovered | Deaths / 100 Cases | Recovered / 100 Cases | Deaths / 100 Recovered | Confirmed last week | 1 week change | 1 week % increase | WHO Region            |
|-----|--------------------|-----------|--------|-----------|--------|-----------|------------|---------------|--------------------|-----------------------|------------------------|---------------------|---------------|-------------------|-----------------------|
| 0   | Afghanistan        | 36263     | 1269   | 25198     | 9796   | 106       | 10         | 18            | 3.50               | 69.49                 | 5.04                   | 35526               | 737           | 2.07              | Eastern Mediterranean |
| 1   | Albania            | 4880      | 144    | 2745      | 1991   | 117       | 6          | 63            | 2.95               | 56.25                 | 5.25                   | 4171                | 709           | 17.00             | Europe                |
| 2   | Algeria            | 27973     | 1163   | 18837     | 7973   | 616       | 8          | 749           | 4.16               | 67.34                 | 6.17                   | 23691               | 4282          | 18.07             | Africa                |
| 3   | Andorra            | 907       | 52     | 803       | 52     | 10        | 0          | 0             | 5.73               | 88.53                 | 6.48                   | 884                 | 23            | 2.60              | Europe                |
| 4   | Angola             | 950       | 41     | 242       | 667    | 18        | 1          | 0             | 4.32               | 25.47                 | 16.94                  | 749                 | 201           | 26.84             | Africa                |
| ... | ...                | ...       | ...    | ...       | ...    | ...       | ...        | ...           | ...                | ...                   | ...                    | ...                 | ...           | ...               | ...                   |
| 182 | West Bank and Gaza | 10621     | 78     | 3752      | 6791   | 152       | 2          | 0             | 0.73               | 35.33                 | 2.08                   | 8916                | 1705          | 19.12             | Eastern Mediterranean |
| 183 | Western Sahara     | 10        | 1      | 8         | 1      | 0         | 0          | 0             | 10.00              | 80.00                 | 12.50                  | 10                  | 0             | 0.00              | Africa                |
| 184 | Yemen              | 1691      | 483    | 833       | 375    | 10        | 4          | 36            | 28.56              | 49.26                 | 57.98                  | 1619                | 72            | 4.45              | Eastern Mediterranean |
| 185 | Zambia             | 4552      | 140    | 2815      | 1597   | 71        | 1          | 465           | 3.08               | 61.84                 | 4.97                   | 3326                | 1226          | 36.86             | Africa                |
| 186 | Zimbabwe           | 2704      | 36     | 542       | 2126   | 192       | 2          | 24            | 1.33               | 20.04                 | 6.64                   | 1713                | 991           | 57.85             | Africa                |

187 rows × 15 columns

In \[7\]:

    df.head()

Out\[7\]:

|     | Country/Region | Confirmed | Deaths | Recovered | Active | New cases | New deaths | New recovered | Deaths / 100 Cases | Recovered / 100 Cases | Deaths / 100 Recovered | Confirmed last week | 1 week change | 1 week % increase | WHO Region            |
|-----|----------------|-----------|--------|-----------|--------|-----------|------------|---------------|--------------------|-----------------------|------------------------|---------------------|---------------|-------------------|-----------------------|
| 0   | Afghanistan    | 36263     | 1269   | 25198     | 9796   | 106       | 10         | 18            | 3.50               | 69.49                 | 5.04                   | 35526               | 737           | 2.07              | Eastern Mediterranean |
| 1   | Albania        | 4880      | 144    | 2745      | 1991   | 117       | 6          | 63            | 2.95               | 56.25                 | 5.25                   | 4171                | 709           | 17.00             | Europe                |
| 2   | Algeria        | 27973     | 1163   | 18837     | 7973   | 616       | 8          | 749           | 4.16               | 67.34                 | 6.17                   | 23691               | 4282          | 18.07             | Africa                |
| 3   | Andorra        | 907       | 52     | 803       | 52     | 10        | 0          | 0             | 5.73               | 88.53                 | 6.48                   | 884                 | 23            | 2.60              | Europe                |
| 4   | Angola         | 950       | 41     | 242       | 667    | 18        | 1          | 0             | 4.32               | 25.47                 | 16.94                  | 749                 | 201           | 26.84             | Africa                |

In \[8\]:

    df.tail()

Out\[8\]:

|     | Country/Region     | Confirmed | Deaths | Recovered | Active | New cases | New deaths | New recovered | Deaths / 100 Cases | Recovered / 100 Cases | Deaths / 100 Recovered | Confirmed last week | 1 week change | 1 week % increase | WHO Region            |
|-----|--------------------|-----------|--------|-----------|--------|-----------|------------|---------------|--------------------|-----------------------|------------------------|---------------------|---------------|-------------------|-----------------------|
| 182 | West Bank and Gaza | 10621     | 78     | 3752      | 6791   | 152       | 2          | 0             | 0.73               | 35.33                 | 2.08                   | 8916                | 1705          | 19.12             | Eastern Mediterranean |
| 183 | Western Sahara     | 10        | 1      | 8         | 1      | 0         | 0          | 0             | 10.00              | 80.00                 | 12.50                  | 10                  | 0             | 0.00              | Africa                |
| 184 | Yemen              | 1691      | 483    | 833       | 375    | 10        | 4          | 36            | 28.56              | 49.26                 | 57.98                  | 1619                | 72            | 4.45              | Eastern Mediterranean |
| 185 | Zambia             | 4552      | 140    | 2815      | 1597   | 71        | 1          | 465           | 3.08               | 61.84                 | 4.97                   | 3326                | 1226          | 36.86             | Africa                |
| 186 | Zimbabwe           | 2704      | 36     | 542       | 2126   | 192       | 2          | 24            | 1.33               | 20.04                 | 6.64                   | 1713                | 991           | 57.85             | Africa                |

In \[9\]:

    df.isnull()

Out\[9\]:

|     | Country/Region | Confirmed | Deaths | Recovered | Active | New cases | New deaths | New recovered | Deaths / 100 Cases | Recovered / 100 Cases | Deaths / 100 Recovered | Confirmed last week | 1 week change | 1 week % increase | WHO Region |
|-----|----------------|-----------|--------|-----------|--------|-----------|------------|---------------|--------------------|-----------------------|------------------------|---------------------|---------------|-------------------|------------|
| 0   | False          | False     | False  | False     | False  | False     | False      | False         | False              | False                 | False                  | False               | False         | False             | False      |
| 1   | False          | False     | False  | False     | False  | False     | False      | False         | False              | False                 | False                  | False               | False         | False             | False      |
| 2   | False          | False     | False  | False     | False  | False     | False      | False         | False              | False                 | False                  | False               | False         | False             | False      |
| 3   | False          | False     | False  | False     | False  | False     | False      | False         | False              | False                 | False                  | False               | False         | False             | False      |
| 4   | False          | False     | False  | False     | False  | False     | False      | False         | False              | False                 | False                  | False               | False         | False             | False      |
| ... | ...            | ...       | ...    | ...       | ...    | ...       | ...        | ...           | ...                | ...                   | ...                    | ...                 | ...           | ...               | ...        |
| 182 | False          | False     | False  | False     | False  | False     | False      | False         | False              | False                 | False                  | False               | False         | False             | False      |
| 183 | False          | False     | False  | False     | False  | False     | False      | False         | False              | False                 | False                  | False               | False         | False             | False      |
| 184 | False          | False     | False  | False     | False  | False     | False      | False         | False              | False                 | False                  | False               | False         | False             | False      |
| 185 | False          | False     | False  | False     | False  | False     | False      | False         | False              | False                 | False                  | False               | False         | False             | False      |
| 186 | False          | False     | False  | False     | False  | False     | False      | False         | False              | False                 | False                  | False               | False         | False             | False      |

187 rows × 15 columns

In \[10\]:

    df.isnull().sum()

Out\[10\]:

    Country/Region            0
    Confirmed                 0
    Deaths                    0
    Recovered                 0
    Active                    0
    New cases                 0
    New deaths                0
    New recovered             0
    Deaths / 100 Cases        0
    Recovered / 100 Cases     0
    Deaths / 100 Recovered    0
    Confirmed last week       0
    1 week change             0
    1 week % increase         0
    WHO Region                0
    dtype: int64

In \[11\]:

    df.describe()

Out\[11\]:

|       | Confirmed    | Deaths        | Recovered    | Active       | New cases    | New deaths  | New recovered | Deaths / 100 Cases | Recovered / 100 Cases | Deaths / 100 Recovered | Confirmed last week | 1 week change | 1 week % increase |
|-------|--------------|---------------|--------------|--------------|--------------|-------------|---------------|--------------------|-----------------------|------------------------|---------------------|---------------|-------------------|
| count | 1.870000e+02 | 187.000000    | 1.870000e+02 | 1.870000e+02 | 187.000000   | 187.000000  | 187.000000    | 187.000000         | 187.000000            | 187.00                 | 1.870000e+02        | 187.000000    | 187.000000        |
| mean  | 8.813094e+04 | 3497.518717   | 5.063148e+04 | 3.400194e+04 | 1222.957219  | 28.957219   | 933.812834    | 3.019519           | 64.820535             | inf                    | 7.868248e+04        | 9448.459893   | 13.606203         |
| std   | 3.833187e+05 | 14100.002482  | 1.901882e+05 | 2.133262e+05 | 5710.374790  | 120.037173  | 4197.719635   | 3.454302           | 26.287694             | NaN                    | 3.382737e+05        | 47491.127684  | 24.509838         |
| min   | 1.000000e+01 | 0.000000      | 0.000000e+00 | 0.000000e+00 | 0.000000     | 0.000000    | 0.000000      | 0.000000           | 0.000000              | 0.00                   | 1.000000e+01        | -47.000000    | -3.840000         |
| 25%   | 1.114000e+03 | 18.500000     | 6.265000e+02 | 1.415000e+02 | 4.000000     | 0.000000    | 0.000000      | 0.945000           | 48.770000             | 1.45                   | 1.051500e+03        | 49.000000     | 2.775000          |
| 50%   | 5.059000e+03 | 108.000000    | 2.815000e+03 | 1.600000e+03 | 49.000000    | 1.000000    | 22.000000     | 2.150000           | 71.320000             | 3.62                   | 5.020000e+03        | 432.000000    | 6.890000          |
| 75%   | 4.046050e+04 | 734.000000    | 2.260600e+04 | 9.149000e+03 | 419.500000   | 6.000000    | 221.000000    | 3.875000           | 86.885000             | 6.44                   | 3.708050e+04        | 3172.000000   | 16.855000         |
| max   | 4.290259e+06 | 148011.000000 | 1.846641e+06 | 2.816444e+06 | 56336.000000 | 1076.000000 | 33728.000000  | 28.560000          | 100.000000            | inf                    | 3.834677e+06        | 455582.000000 | 226.320000        |

In \[12\]:

    df.size

Out\[12\]:

    2805

In \[13\]:

    df.shape

Out\[13\]:

    (187, 15)

In \[14\]:

    df.info()

    <class 'pandas.core.frame.DataFrame'>
    RangeIndex: 187 entries, 0 to 186
    Data columns (total 15 columns):
     #   Column                  Non-Null Count  Dtype  
    ---  ------                  --------------  -----  
     0   Country/Region          187 non-null    object 
     1   Confirmed               187 non-null    int64  
     2   Deaths                  187 non-null    int64  
     3   Recovered               187 non-null    int64  
     4   Active                  187 non-null    int64  
     5   New cases               187 non-null    int64  
     6   New deaths              187 non-null    int64  
     7   New recovered           187 non-null    int64  
     8   Deaths / 100 Cases      187 non-null    float64
     9   Recovered / 100 Cases   187 non-null    float64
     10  Deaths / 100 Recovered  187 non-null    float64
     11  Confirmed last week     187 non-null    int64  
     12  1 week change           187 non-null    int64  
     13  1 week % increase       187 non-null    float64
     14  WHO Region              187 non-null    object 
    dtypes: float64(4), int64(9), object(2)
    memory usage: 22.0+ KB

In \[15\]:

    df.dtypes

Out\[15\]:

    Country/Region             object
    Confirmed                   int64
    Deaths                      int64
    Recovered                   int64
    Active                      int64
    New cases                   int64
    New deaths                  int64
    New recovered               int64
    Deaths / 100 Cases        float64
    Recovered / 100 Cases     float64
    Deaths / 100 Recovered    float64
    Confirmed last week         int64
    1 week change               int64
    1 week % increase         float64
    WHO Region                 object
    dtype: object

In \[16\]:

    df['Deaths'] = df['Deaths'].astype ("float64")
    df.dtypes

Out\[16\]:

    Country/Region             object
    Confirmed                   int64
    Deaths                    float64
    Recovered                   int64
    Active                      int64
    New cases                   int64
    New deaths                  int64
    New recovered               int64
    Deaths / 100 Cases        float64
    Recovered / 100 Cases     float64
    Deaths / 100 Recovered    float64
    Confirmed last week         int64
    1 week change               int64
    1 week % increase         float64
    WHO Region                 object
    dtype: object

In \[17\]:

    df['WHO Region'].replace({'Africa':0,'Europe':1,'Eastern Mediterranean':2},inplace=True)
    df

Out\[17\]:

|     | Country/Region     | Confirmed | Deaths | Recovered | Active | New cases | New deaths | New recovered | Deaths / 100 Cases | Recovered / 100 Cases | Deaths / 100 Recovered | Confirmed last week | 1 week change | 1 week % increase | WHO Region |
|-----|--------------------|-----------|--------|-----------|--------|-----------|------------|---------------|--------------------|-----------------------|------------------------|---------------------|---------------|-------------------|------------|
| 0   | Afghanistan        | 36263     | 1269.0 | 25198     | 9796   | 106       | 10         | 18            | 3.50               | 69.49                 | 5.04                   | 35526               | 737           | 2.07              | 2          |
| 1   | Albania            | 4880      | 144.0  | 2745      | 1991   | 117       | 6          | 63            | 2.95               | 56.25                 | 5.25                   | 4171                | 709           | 17.00             | 1          |
| 2   | Algeria            | 27973     | 1163.0 | 18837     | 7973   | 616       | 8          | 749           | 4.16               | 67.34                 | 6.17                   | 23691               | 4282          | 18.07             | 0          |
| 3   | Andorra            | 907       | 52.0   | 803       | 52     | 10        | 0          | 0             | 5.73               | 88.53                 | 6.48                   | 884                 | 23            | 2.60              | 1          |
| 4   | Angola             | 950       | 41.0   | 242       | 667    | 18        | 1          | 0             | 4.32               | 25.47                 | 16.94                  | 749                 | 201           | 26.84             | 0          |
| ... | ...                | ...       | ...    | ...       | ...    | ...       | ...        | ...           | ...                | ...                   | ...                    | ...                 | ...           | ...               | ...        |
| 182 | West Bank and Gaza | 10621     | 78.0   | 3752      | 6791   | 152       | 2          | 0             | 0.73               | 35.33                 | 2.08                   | 8916                | 1705          | 19.12             | 2          |
| 183 | Western Sahara     | 10        | 1.0    | 8         | 1      | 0         | 0          | 0             | 10.00              | 80.00                 | 12.50                  | 10                  | 0             | 0.00              | 0          |
| 184 | Yemen              | 1691      | 483.0  | 833       | 375    | 10        | 4          | 36            | 28.56              | 49.26                 | 57.98                  | 1619                | 72            | 4.45              | 2          |
| 185 | Zambia             | 4552      | 140.0  | 2815      | 1597   | 71        | 1          | 465           | 3.08               | 61.84                 | 4.97                   | 3326                | 1226          | 36.86             | 0          |
| 186 | Zimbabwe           | 2704      | 36.0   | 542       | 2126   | 192       | 2          | 24            | 1.33               | 20.04                 | 6.64                   | 1713                | 991           | 57.85             | 0          |

187 rows × 15 columns

In \[ \]: